[package]
name = "colourme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# colour_utils = { git = "https://github.com/lukamanitta/colour_utils.git" }
colour_utils = { path = "../colour_utils" }
toml = "0.8.8"
regex = "1.10.4"
rand = "0.10.1"
clap = { version = "4.6", features = ["derive", "env"] }
